### ISSUE TITLE
How many Apps

### ISSUE THREAD

**Issue by raunitkumar** [lighttt/Shop-Venue#1]
Have u created 2 apps, one for the users and other for the admin? If not then how are u updating the data in the database for the user app?

**Comment by lighttt** [comment]
No I havent created two apps. Its the same app. For user and admin I have adjusted in the firebase according to user type. So if its user type admin the app can only browse products and if its admin it can managed the products.

**Comment by raunitkumar** [comment]
Thank u brother.. Means a lot🙏
